<div class="row">
    <div class="col-md-12">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h3 class="m-0">Dashboard</h3>
            </div>
        </div>

        <div class="row p-1">
            <div class="col-2">
                <button class="btn btn-success btn-block btn-sm"><i class="fa fa-unlock"></i> Liberar todas</button>
            </div>
            <div class="col-2">
                <button class="btn btn-danger btn-block btn-sm"><i class="fa fa-lock"></i> Bloquear todas</button>
            </div>
        </div>

        @php
        $permissiones = [
            'Dashboard' => [ 
                'Tela inicial' => [
                    'Mostrar contas a receber',
                    'Mostrar contas a pagar',
                    'Mostrar previsão de caixa',
                    'Mostrar fluxo de caixa',
                    'Mostrar vendas aprovadas',
                    'Mostrar contas bancárias',
                    'Mostrar agenda',
                ],
            ],
            'Cadastros' => [ 
                'Clientes' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Acessar de outras lojas',
                    'Acessar de outros funcionários',
                    'Exportar cadastros',
                    'Exportar emails',
                    'Importar cadastros',
                ], 
                'Fornecedores' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Exportar excel',
                    'Importar castrados',
                ],
                'Transportadoras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Funcionários' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Campos extras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Tipos de contatos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Tipos de endereços' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ],
            ],
            'Produtos' => [ 
                'Produtos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Clonar',
                    'Visualizar valor de custo',
                    'Movimentações de estoque',
                    'Ajustar valores em massa',
                    'Importar cadastros',
                    'Ajustar produtos em massa',
                    'Visualizar estoque de outras lojas',
                    'Exportar excel',
                ], 
                'Valores de venda' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Etiquetas' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Gerar etiquetas',
                ], 
                'Grupos de produtos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Grades/variações' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Unidades de produtos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Campos extras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ],
            ],
            'Serviços' => [ 
                'Serviços' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Visualizar valor de custo',
                ],
            ],
            'Orçamentos' => [ 
                'Orçamentos de produtos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Imprimir PDF',
                    'Alterar situação',
                    'Enviar orçamento por e-mail',
                    'Alterar valor venda',
                    'Indicar vendedor',
                    'Acessar de outros funcionários',
                    'Conceder desconto',
                    'Exportar excel',
                ], 
                'Orçamentos de serviços' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Imprimir PDF',
                    'Enviar orçamento por e-mail',
                    'Alterar situação',
                    'Indicar vendedor',
                    'Acessar de outros funcionários',
                    'Exportar excel',
                    'Alterar valor venda',
                    'Conceder desconto',
                ], 
                'Campos extras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Situações' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ],
            ],
            'Vendas' => [ 
                'Vendas de produtos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Imprimir pedido',
                    'Alterar situação',
                    'Indicar vendedor',
                    'Acessar de outros funcionários',
                    'Enviar venda por e-mail',
                    'Alterar valor venda',
                    'Conceder desconto',
                    'Exportar excel',
                    'Imprimir ordem de produção',
                    'Agrupar vendas',
                    'Faturamento parcial',
                ], 
                'Vendas no balcão' => [
                    'Listar',
                    'Vender',
                    'Editar',
                    'Visualizar detalhes',
                    'Imprimir cupom',
                    'Imprimir PDF',
                    'Deletar',
                    'Enviar venda por e-mail',
                    'Alterar situação',
                    'Indicar vendedor',
                    'Alterar valor venda',
                    'Conceder desconto',
                    'Exportar excel',
                    'Agrupar vendas',
                    'Acessar de outros funcionários',
                ], 
                'Vendas de serviços' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Imprimir pedido',
                    'Alterar situação',
                    'Indicar vendedor',
                    'Acessar de outros funcionários',
                    'Enviar venda por e-mail',
                    'Alterar valor venda',
                    'Conceder desconto',
                    'Exportar excel',
                    'Agrupar vendas',
                    'Imprimir ordem serviço',
                    'Faturamento parcial',
                ], 
                
                'Campos extras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Balanças' => [
                    'Listar',
                    'Visualizar',
                    'Adicionar',
                    'Editar',
                    'Deletar',
                    'Visualizar produtos vinculados',
                    'Importar vínculos via Excel',
                    'Vincular produtos',
                    'Editar vínculo',
                    'Desvincular',
                    'Exportar',
                ], 
                'Canais de vendas' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Situações de vendas' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ],
            ],
            'Contratos' => [ 
                'Contratos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Exportar excel',
                    'Alterar situação',
                    'Indicar vendedor',
                    'Acessar de outros funcionários',
                    'Imprimir PDF',
                    'Visualizar notas fiscais',
                ], 
                'Locações' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Exportar excel',
                    'Indicar vendedor',
                    'Acessar de outros funcionários',
                    'Alterar situação',
                    'Imprimir PDF',
                    'Devolução parcial',
                    'Listar devoluções',
                    'Cancelar devolução',
                    'Enviar contrato por e-mail',
                ], 
                'Assinaturas' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Indicar vendedor',
                    'Acessar de outros funcionários',
                    'Alterar situação',
                    'Exportar excel',
                ], 
                'Campos extras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Situações de contratos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Situações de locações' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ],
            ],
            'Ordens de serviços' => [ 
                'Ordens de serviços' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Imprimir PDF',
                    'Alterar situação',
                    'Indicar responsável',
                    'Acessar de outros funcionários',
                    'Alterar valor venda',
                    'Conceder desconto',
                    'Enviar os email',
                    'Exportar excel',
                    'Imprimir ordem de produção',
                    'Adicionar atividade',
                    'Editar atividade',
                    'Deletar atividade',
                    'Imprimir etiqueta',
                    'Complementar os',
                ], 
                'Campos extras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Painel' => [
                    'Listar',
                    'Mostrar vendas aprovadas',
                    'Mostrar vendas de funcionários',
                    'Mostrar prazos',
                    'Mostrar prioridades',
                ], 
                'Situações de OS' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ],
            ],
            'Notas fiscais' => [ 
                'NF-e' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Emitir nota fiscal',
                    'Imprimir danfe',
                    'Cancelar nota fiscal',
                    'Baixar xml',
                    'Enviar por email',
                    'Acessar de outros funcionários',
                    'Listar cartas de correções',
                    'Gerar carta de correção',
                    'Imprimir carta de correção',
                    'Baixar XML de carta de correção',
                    'Listar inutilizações de numerações',
                    'Inutilizar numeração',
                    'Exportar xml',
                    'Importar xml',
                    'Exportar excel',
                ], 
                'NFC-e' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Exportar excel',
                    'Emitir nota fiscal',
                    'Imprimir danfe',
                    'Baixar xml',
                    'Enviar por email',
                    'Cancelar nota fiscal',
                    'Exportar xml',
                    'Acessar de outros funcionários',
                    'Listar inutilizações de numerações',
                    'Inutilizar numeração',
                ], 
                'NFS-e' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Exportar excel',
                    'Enviar por email',
                    'Emitir nota fiscal',
                    'Cancelar nota fiscal',
                    'Baixar xml',
                    'Imprimir danfe',
                    'Acessar de outros funcionários',
                ], 
                'Naturezas de operações' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Tributações' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Atividades de serviços' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Intermediadores' => [
                    'Listar',
                    'Visualizar',
                    'Adicionar',
                    'Editar',
                    'Deletar',
                ], 
                'NCM' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Importar NCM',
                ],
            ],
            'Estoque' => [ 
                'Ajustes de estoque' => [
                    'Listar',
                    'Adicionar',
                    'Visualizar detalhes',
                ], 
                'Devoluções' => [
                    'Listar',
                    'Adicionar',
                    'Visualizar detalhes',
                    'Cancelar',
                ], 
                'Campos extras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Compras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Listar notas de compras',
                    'Deletar notas de compras',
                    'Imprimir PDF',
                    'Enviar compra por e-mail',
                    'Alterar situação',
                    'Indicar vendedor',
                    'Acessar de outros funcionários',
                    'Exportar excel',
                    'Importar xml',
                    'Baixar xml',
                    'Conceder desconto',
                ], 
                'Cotações' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Imprimir PDF',
                    'Enviar cotação por e-mail',
                    'Acessar de outros funcionários',
                    'Exportar excel',
                ], 
                'Situações de compras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Transferências de estoque' => [
                    'Listar',
                    'Adicionar',
                    'Visualizar detalhes',
                    'Imprimir PDF',
                ],
            ],
            'Financeiro' => [ 
                'Movimentações financeiras' => [
                    'Listar pagamentos',
                    'Adicionar pagamento',
                    'Editar pagamento',
                    'Visualizar pagamento',
                    'Deletar pagamento',
                    'Confirmar pagamento',
                    'Cancelar confirmação de pagamento',
                    'Listar recebimentos',
                    'DRE gerencial',
                    'Adicionar recebimento',
                    'Editar recebimento',
                    'Visualizar recebimento',
                    'Deletar recebimento',
                    'Confirmar recebimento',
                    'Cancelar confirmação de recebimento',
                    'Acessar de outros funcionários',
                    'Acessar fluxo de caixa',
                    'Transferências entre contas',
                    'Conciliar extrato bancário',
                    'Listar boletos bancários',
                    'Visualizar boleto e link de pagamento',
                    'Enviar cobrança por e-mail',
                    'Exportar remessa',
                    'Importar arquivos de retorno',
                    'Imprimir fatura',
                    'Imprimir recibo',
                    'Deletar anexo(comprovante)',
                    'Importar cadastros',
                    'Exportar excel',
                ], 
                'Conta bancária' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Formas de pagamento' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Planos de contas' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Centros de custos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Caixas' => [
                    'Listar',
                    'Visualizar detalhes',
                    'Imprimir PDF',
                    'Acessar de outros funcionários',
                    'Abrir caixa',
                    'Fechar caixa',
                    'Realizar sangria',
                    'Realizar reforço',
                ],
                'Tabelas de rateios' => [
                    'Listar',
                    'Visualizar',
                    'Adicionar',
                    'Editar',
                    'Deletar',
                ],
                'Campos extras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Situações' => [
                    'Listar',
                    'Visualizar',
                    'Adicionar',
                    'Editar',
                    'Deletar',
                ],
            ],
            'Atendimentos' => [ 
                'Atendimentos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Acessar de outros funcionários',
                    'Responder atendimento',
                    'Adicionar historico',
                    'Indicar atendente',
                    'Imprimir PDF',
                    'Exportar excel',
                ], 
                'Assuntos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Formas de atendimento' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Campos extras' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Situações' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ],
            ],
            'Agenda' => [ 
                'Agendamentos' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Alterar situação',
                    'Acessar de outros funcionários',
                    'Indicar responsáveis',
                ], 
                'Situações' => [
                    'Listar',
                    'Visualizar detalhes',
                    'Adicionar',
                    'Editar',
                    'Deletar',
                ],
            ],
            'Relatórios' => [ 
                'Cadastros' => [
                    'Selecionar relatório',
                    'Relatório de clientes',
                    'Relatório de fornecedores',
                    'Relatório de transportadoras',
                    'Relatório de produtos',
                    'Relatório de serviços',
                    'Relatório de aniversariantes',
                    'Relatório de funcionários',
                ], 
                'Vendas' => [
                    'Selecionar relatório',
                    'Relatório de orçamentos',
                    'Relatório de vendas',
                    'Relatorio produtos vendidos',
                    'Relatório de clientes que mais compram',
                    'Relatório de comissão por venda',
                    'Relatorio servicos vendidos',
                    'Relatório de comissão por produto',
                    'Relatório de comissão por serviço',
                    'Relatório de devoluções',
                    'Relatório de produtos devolvidos',
                ], 
                'Ordens de serviços' => [
                    'Listar',
                    'Relatório de ordens de serviços',
                    'Relatório de equipamentos',
                    'Relatorio tempo situacao',
                    'Relatório de comissão por venda',
                    'Relatório de comissão de técnicos',
                ], 
                'Estoque' => [
                    'Selecionar relatório',
                    'Relatório de cotações',
                    'Relatório de compras',
                    'Relatório de estoque de produtos',
                    'Relatório de produtos comprados',
                    'Relatório de serviços contratados',
                    'Inventário de estoque',
                ], 
                'Financeiro' => [
                    'Selecionar relatório',
                    'Relatório de contas a pagar',
                    'Relatório de contas a receber',
                    'Relatório de extrato',
                    'Relatório de centro de custo',
                    'Relatório de comissão por venda',
                    'Relatório DRE',
                    'Relatório de contas bancárias',
                ], 
                'Contratos' => [
                    'Listar',
                    'Locações do cliente',
                    'Devoluções de produtos',
                    'Relatório de serviços',
                    'Relatório de comissão de vendedores',
                    'Relatório de produtos locados',
                    'Relatório de assinaturas',
                ],
                'Notas Fiscais' => [
                    'Listar',
                    'NF-e',
                    'NFC-e',
                    'NFS-e',
                ], 
                'Agendamentos' => [
                    'Listar',
                    'Relatório de agendamentos',
                ], 
                'Atendimentos' => [
                    'Listar',
                    'Relatório de atendimentos',
                ], 
                'Logs do sistema' => [
                    'Listar',
                ],
            ],
            'Meu contador' => [ 
                'Mensagens' => [
                    'Listar',
                    'Visualizar detalhes',
                    'Deletar',
                    'Enviar mensagem',
                ],
            ],
            'Configurações' => [ 
                'Configurações' => [
                    'Adicionar certificado digital',
                    'Alterar dados da empresa',
                    'Deletar certificado digital',
                    'Editar marca da empresa',
                    'Configurações gerais',
                ], 
                'Planos' => [
                    'Meu plano',
                ], 
                'Grupos de usuários' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Usuários' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Permissões' => [
                    'Gerenciar grupos',
                    'Gerenciar usuários',
                ], 
                'Empresas / Lojas' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ], 
                'Avisos por e-mail' => [
                    'Listar',
                    'Adicionar',
                    'Editar',
                    'Visualizar detalhes',
                    'Deletar',
                ],
                'Modelos de e-mails' => [
                    'Listar',
                    'Editar',
                    'Visualizar detalhes',
                ],
            ],
        ];
        @endphp
    
        <div class="row">
            @foreach($permissiones as $menu => $submenu)
            <div class="col-3">
                <div class="card" style="max-height: 400px;">
                    <div class="card-header">
                        <h3 class="card-title">{{ $menu }}</h3>
                        {{--
                        <div class="card-tools">
                            <span title="3 New Messages" class="badge badge-primary">3</span>
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" title="Contacts" data-widget="chat-pane-toggle">
                                <i class="fas fa-comments"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                        --}}
                    </div>
                    <div class="card-body p-1" style="overflow-y: auto;">
                        @foreach($submenu as $aaa => $bbb)
                        <h4>{{ $aaa }}</h4>
                        <table class="table table-sm table-bordered table-striped">
                            <tbody>
                                @foreach($bbb as $ccc => $ddd)
                                <tr>
                                    <td>{{ $ddd }}</td>
                                    <td> </td>
                                </tr>
                                @endforeach
                                <br>
                            </tbody>
                        </table>
                        @endforeach
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>
